#!/usr/bin/env python3
"""Assemble the GitHub Pages site for safe-query-lab.

Produces a small themed static site around the aggregated Javadocs:

  <out>/
    index.html                landing page
    implementation-notes.html rendered from docs/implementation-notes.md
    benchmarks.html           JMH results with inline SVG charts
    docs.css                  shared theme (teal/slate, matches the Javadoc theme)
    apidocs/                  the aggregate Javadocs (copied from --apidocs)

Everything is self-contained: no CDN, no build-time dependencies beyond the
Python standard library, so it renders identically locally and on Pages.

Usage:
    python3 scripts/build-docs.py --apidocs target/reports/apidocs --out site
"""

import argparse
import glob
import html
import json
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Per-engine categorical colors for chart bars (chrome stays teal; data ink is
# categorical so the eye can track one engine across charts).
ENGINE_COLORS = {
    "jdbc": "#0f766e",
    "jpa": "#7c3aed",
    "querydsl": "#2563eb",
    "jooq": "#d97706",
    "mybatis": "#db2777",
}

SHARED_CSS = """
:root {
  --accent: #0f766e;
  --accent-dark: #115e59;
  --text: #1f2937;
  --muted: #64748b;
  --bg: #f8fafc;
  --surface: #ffffff;
  --border: #e5e7eb;
  --code-bg: #eef2f7;
}
* { box-sizing: border-box; }
body {
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.6;
  margin: 0;
  background: var(--bg);
}
header.site {
  background: var(--accent);
  color: #fff;
  padding: 18px 24px;
}
header.site a { color: #fff; text-decoration: none; font-weight: 600; margin-right: 20px; opacity: .9; }
header.site a:hover { opacity: 1; text-decoration: underline; }
header.site .brand { font-weight: 800; margin-right: 28px; }
main { max-width: 920px; margin: 0 auto; padding: 40px 24px 72px; }
h1 { font-size: 2.3rem; margin: 0 0 8px; letter-spacing: -0.02em; }
h2 { font-size: 1.5rem; margin: 40px 0 12px; padding-bottom: 6px; border-bottom: 2px solid var(--accent); }
h3 { font-size: 1.15rem; margin: 28px 0 8px; color: var(--accent-dark); }
p, li { font-size: 1.02rem; }
a { color: var(--accent); font-weight: 600; }
.lede { font-size: 1.12rem; color: var(--muted); }
section.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  margin-top: 22px;
  padding: 22px 26px;
}
code {
  background: var(--code-bg);
  border-radius: 4px;
  padding: 2px 5px;
  font-family: "SFMono-Regular", ui-monospace, Menlo, Consolas, monospace;
  font-size: 0.92em;
}
pre {
  background: #0f172a;
  color: #e2e8f0;
  border-radius: 8px;
  padding: 16px 18px;
  overflow-x: auto;
}
pre code { background: none; color: inherit; padding: 0; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 0.95rem; }
th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid var(--border); }
th { background: #e8f0ef; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.chart { margin: 8px 0 4px; }
.chart svg { max-width: 100%; height: auto; }
.legend { display: flex; flex-wrap: wrap; gap: 14px; margin: 6px 0 18px; font-size: 0.9rem; color: var(--muted); }
.legend span { display: inline-flex; align-items: center; gap: 6px; }
.legend i { width: 12px; height: 12px; border-radius: 3px; display: inline-block; }
.note { background: #ecfdf5; border-left: 4px solid var(--accent); padding: 12px 16px; border-radius: 4px; margin: 18px 0; }
footer { color: var(--muted); font-size: 0.85rem; padding: 24px; text-align: center; }
"""

NAV = """<header class="site">
  <a class="brand" href="index.html">safe-query-lab</a>
  <a href="apidocs/index.html">Javadocs</a>
  <a href="benchmarks.html">Benchmarks</a>
  <a href="implementation-notes.html">Implementation notes</a>
</header>"""


def page(title, body):
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<link rel="stylesheet" href="docs.css">
</head>
<body>
{NAV}
<main>
{body}
</main>
<footer>safe-query-lab &middot; generated by scripts/build-docs.py</footer>
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# Minimal Markdown -> HTML (only the constructs implementation-notes.md uses)
# --------------------------------------------------------------------------- #
def md_inline(text):
    text = html.escape(text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def md_to_html(md):
    lines = md.splitlines()
    out = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]

        # fenced code block
        if line.startswith("```"):
            i += 1
            buf = []
            while i < n and not lines[i].startswith("```"):
                buf.append(html.escape(lines[i]))
                i += 1
            i += 1  # closing fence
            out.append("<pre><code>" + "\n".join(buf) + "</code></pre>")
            continue

        # headings
        m = re.match(r"(#{1,3})\s+(.*)", line)
        if m:
            level = len(m.group(1))
            out.append(f"<h{level}>{md_inline(m.group(2))}</h{level}>")
            i += 1
            continue

        # unordered list (with 2-space-indented continuation lines)
        if re.match(r"[-*]\s+", line):
            items = []
            while i < n and (re.match(r"[-*]\s+", lines[i]) or (lines[i].startswith("  ") and lines[i].strip())):
                if re.match(r"[-*]\s+", lines[i]):
                    items.append(re.sub(r"[-*]\s+", "", lines[i], count=1))
                else:
                    items[-1] += " " + lines[i].strip()
                i += 1
            out.append("<ul>" + "".join(f"<li>{md_inline(t)}</li>" for t in items) + "</ul>")
            continue

        # blank line
        if not line.strip():
            i += 1
            continue

        # paragraph (gather until blank / block start)
        buf = [line]
        i += 1
        while i < n and lines[i].strip() and not re.match(r"(#{1,3}\s|[-*]\s|```)", lines[i]):
            buf.append(lines[i])
            i += 1
        out.append("<p>" + md_inline(" ".join(buf)) + "</p>")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Inline SVG horizontal bar chart (no external libraries)
# --------------------------------------------------------------------------- #
def hbar_chart(rows, unit, fmt):
    """rows: list of (label, value, error, color). Returns an <svg> string."""
    width = 720
    row_h = 40
    pad_top = 12
    pad_bottom = 8
    label_w = 150
    val_w = 120
    bar_max = width - label_w - val_w - 20
    height = pad_top + pad_bottom + row_h * len(rows)
    vmax = max(v for _, v, _, _ in rows) or 1

    parts = [
        f'<svg viewBox="0 0 {width} {height}" role="img" xmlns="http://www.w3.org/2000/svg" font-family="-apple-system, Segoe UI, sans-serif">'
    ]
    for idx, (label, value, error, color) in enumerate(rows):
        y = pad_top + idx * row_h
        bar_y = y + 6
        bh = row_h - 16
        bw = max(2, bar_max * value / vmax)
        bx = label_w + 8
        parts.append(
            f'<text x="{label_w}" y="{bar_y + bh/2 + 4}" text-anchor="end" font-size="14" fill="#1f2937" font-weight="600">{html.escape(label)}</text>'
        )
        parts.append(
            f'<rect x="{bx}" y="{bar_y}" width="{bw:.1f}" height="{bh}" rx="4" fill="{color}"/>'
        )
        # error whisker
        if error:
            ew = bar_max * error / vmax
            ex = bx + bw
            cy = bar_y + bh / 2
            parts.append(
                f'<line x1="{ex-ew:.1f}" y1="{cy}" x2="{ex+ew:.1f}" y2="{cy}" stroke="#334155" stroke-width="1.5" opacity="0.6"/>'
            )
        parts.append(
            f'<text x="{bx + bw + 8:.1f}" y="{bar_y + bh/2 + 4}" font-size="13" fill="#475569" font-variant-numeric="tabular-nums">{fmt(value)} {unit}</text>'
        )
    parts.append("</svg>")
    return '<div class="chart">' + "".join(parts) + "</div>"


def load_jmh():
    files = sorted(glob.glob(str(REPO / "docs" / "jmh-results-*.json")))
    if not files:
        return None
    data = json.load(open(files[-1]))
    end_to_end = {}   # (engine, scenario) -> (score, error)
    construction = {}  # (bench, scenario) -> (score, error)
    for r in data:
        name = r["benchmark"].split(".")[-1]
        p = r.get("params", {})
        pm = r["primaryMetric"]
        if name == "search":
            end_to_end[(p["engine"], p["scenario"])] = (pm["score"], pm["scoreError"])
        else:
            construction[(name, p["scenario"])] = (pm["score"], pm["scoreError"])
    return {"file": Path(files[-1]).name, "end_to_end": end_to_end, "construction": construction}


def build_benchmarks_page():
    jmh = load_jmh()
    if not jmh:
        return None

    def e2e_rows(scenario, divisor):
        rows = []
        for engine in ["jdbc", "jpa", "querydsl", "jooq", "mybatis"]:
            score, err = jmh["end_to_end"][(engine, scenario)]
            rows.append((engine, score / divisor, err / divisor, ENGINE_COLORS[engine]))
        rows.sort(key=lambda r: r[1])  # fastest first
        return rows

    def con_rows(scenario):
        rows = []
        label_map = {"jdbcStringAssembly": "jdbc", "jooqAstRender": "jooq", "mybatisDynamicSqlRender": "mybatis"}
        for bench, engine in label_map.items():
            score, err = jmh["construction"][(bench, scenario)]
            rows.append((engine, score, err, ENGINE_COLORS[engine]))
        rows.sort(key=lambda r: r[1])
        return rows

    def fmt1(v):
        return f"{v:,.1f}"

    legend = '<div class="legend">' + "".join(
        f'<span><i style="background:{c}"></i>{e}</span>' for e, c in ENGINE_COLORS.items()
    ) + "</div>"

    # full table
    table_rows = ""
    for engine in ["jdbc", "jpa", "querydsl", "jooq", "mybatis"]:
        s = jmh["end_to_end"][(engine, "simple")][0]
        c = jmh["end_to_end"][(engine, "complex")][0]
        table_rows += f'<tr><td>{engine}</td><td class="num">{s:,.1f}</td><td class="num">{c:,.1f}</td></tr>'

    body = f"""<h1>Benchmarks</h1>
<p class="lede">JMH, measured against a 100k-row PostgreSQL. Lower is faster.
Numbers below are from <code>{html.escape(jmh['file'])}</code> — a captured run on
Apple Silicon under a Podman VM, so read the shape, not the absolute values.</p>
{legend}

<section class="card">
<h2>End-to-end latency &mdash; simple query</h2>
<p>One predicate, default sort. Build + execute (count + data) + map, per call.</p>
{hbar_chart(e2e_rows("simple", 1), "&micro;s", fmt1)}
</section>

<section class="card">
<h2>End-to-end latency &mdash; complex query</h2>
<p>Eight predicates + <code>IN</code> + <code>ILIKE</code> + custom sort + page 3.
Shown in milliseconds.</p>
{hbar_chart(e2e_rows("complex", 1000), "ms", fmt1)}
<div class="note"><strong>The surprise:</strong> raw JDBC and jOOQ are the
<em>slowest</em> here, not fastest. It isn't framework overhead &mdash; it's the
query plan. Those two emit <code>ILIKE</code>, which the <code>gin_trgm_ops</code>
index serves; the pattern <code>%ref%</code> matches a third of the table, so the
bitmap index scan + recheck loses to the plain sequential scan the
<code>lower() LIKE</code> engines get. The API you pick shapes the SQL, the SQL
shapes the plan, and the plan is what you pay for.</div>
</section>

<section class="card">
<h2>Query construction only &mdash; no database</h2>
<p>SQL assembly / rendering for the three engines whose SQL is separable from
execution. Nanoseconds per operation, complex scenario.</p>
{hbar_chart(con_rows("complex"), "ns", fmt1)}
<div class="note"><strong>The headline:</strong> construction costs
nanoseconds&ndash;microseconds while a database round trip costs hundreds of
microseconds to milliseconds &mdash; a 1000&times;+ gap. &ldquo;DSL overhead&rdquo;
is noise in any I/O-bound workload. Choose an abstraction for safety and
maintainability, not construction speed.</div>
</section>

<section class="card">
<h2>All end-to-end numbers</h2>
<table>
<tr><th>engine</th><th class="num">simple (&micro;s/op)</th><th class="num">complex (&micro;s/op)</th></tr>
{table_rows}
</table>
<p>Reproduce locally with <code>./mvnw -pl query-benchmarks exec:exec</code>
(≈6&nbsp;min; writes <code>query-benchmarks/results/jmh.json</code>).</p>
</section>
"""
    return page("Benchmarks — safe-query-lab", body)


def build_index():
    body = """<h1>safe-query-lab docs</h1>
<p class="lede">Dynamic transaction search implemented five ways in Java, with a
shared PostgreSQL conformance suite proving the engines behave identically.</p>

<section class="card">
<h2>Browse</h2>
<ul>
<li><a href="apidocs/index.html">Aggregate Javadocs</a> &mdash; every module, cross-linked and searchable</li>
<li><a href="benchmarks.html">Benchmarks</a> &mdash; JMH results with charts</li>
<li><a href="implementation-notes.html">Implementation notes</a> &mdash; a guided map of the inline docs</li>
</ul>
</section>

<section class="card">
<h2>What to read first</h2>
<p>Start with <code>TransactionSearchPort</code> and
<code>TransactionSearchCriteria</code> in the Javadocs &mdash; the one contract all
five engines implement &mdash; then compare the adapters: JDBC, JPA Specifications,
QueryDSL, jOOQ, and MyBatis Dynamic SQL.</p>
</section>"""
    return page("safe-query-lab docs", body)


def build_notes():
    md = (REPO / "docs" / "implementation-notes.md").read_text()
    # Drop the leading H1; the page chrome supplies the title context.
    rendered = md_to_html(md)
    return page("Implementation notes — safe-query-lab", rendered)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apidocs", required=True, help="path to aggregate apidocs dir")
    ap.add_argument("--out", default="site", help="output site directory")
    args = ap.parse_args()

    out = Path(args.out)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    (out / "docs.css").write_text(SHARED_CSS)
    (out / "index.html").write_text(build_index())
    (out / "implementation-notes.html").write_text(build_notes())

    bench = build_benchmarks_page()
    if bench:
        (out / "benchmarks.html").write_text(bench)
        print("wrote benchmarks.html")
    else:
        print("WARNING: no docs/jmh-results-*.json found; skipping benchmarks.html")

    apidocs = Path(args.apidocs)
    if apidocs.is_dir():
        shutil.copytree(apidocs, out / "apidocs")
        print(f"copied {apidocs} -> {out/'apidocs'}")
    else:
        print(f"WARNING: apidocs dir {apidocs} not found; site will lack Javadocs")

    print(f"site assembled at {out}/")


if __name__ == "__main__":
    main()
